# Create a copy of this template file and name it config.yaml .
mysql:
  host: localhost
  user: your_username
  password: your_password
  database: your_database

exclude_tables:
  - table_to_exclude1
  - table_to_exclude2